
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[270] =
    {   0,
        0,    0,  100,   98,   97,    1,   84,   98,   98,   90,
       83,   98,   78,   79,   88,   87,   75,   86,   82,   89,
        8,    8,   76,   72,   91,   77,   92,   95,   96,   80,
       81,   93,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   73,   94,   74,
       85,   27,    0,   17,    0,    0,    0,   32,   74,   28,
       37,    0,    0,   30,   20,   33,   21,   34,   19,    0,
       15,    2,    3,   31,   16,    8,    0,   12,    0,    8,
       81,   73,   80,   22,   24,   26,   25,   23,    0,    0,
       96,   38,   96,   96,   96,   96,   96,   96,   66,   96,

       96,   96,   96,   96,   96,   62,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   39,   29,    0,
        0,   13,   59,    0,   15,    9,    0,   16,   11,    0,
       14,   10,   35,   36,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   67,   96,   47,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,    0,    0,    0,   15,    0,   15,    0,
       16,   14,   10,   43,   96,   60,   45,   96,   96,   96,
       96,   63,   58,   96,   96,   68,   48,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   55,   96,

       96,    0,    0,    0,   15,   70,   53,   96,   96,   96,
       96,   51,   96,   96,   46,   96,   96,   96,   96,   96,
       96,   57,   96,   96,   65,    0,    0,   96,   96,   52,
       41,   96,   71,   49,   18,   42,   56,   64,   96,   96,
       96,    0,    0,   96,   61,   96,   40,   96,   96,    0,
        0,   69,   44,   50,   54,    0,    0,    0,    0,    0,
        0,    5,    7,    0,    0,    7,    4,    6,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    7,    7,    8,
        8,    8,    8,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[279] =
    {   0,
        0,    0,  418,  762,  762,  762,  392,   60,   26,   44,
       61,  378,  762,  762,  379,   57,  762,   58,   56,   66,
       79,   72,  350,  762,   85,  344,   53,  762,   91,  762,
      762,  328,  107,  109,  116,  123,  130,  124,  131,  133,
      136,  139,  145,  138,  146,  154,  147,  762,   62,  762,
      762,  762,   81,  762,  331,  284,  274,  762,  762,  762,
      762,   70,  121,  762,  762,  762,  762,  762,  762,  302,
      166,  762,  762,  762,  182,  187,  207,  185,    0,  217,
      762,  762,  762,  292,  762,  762,  762,  282,   88,  266,
      160,  762,  167,  178,  222,  232,  234,  240,  241,  246,

      247,  252,  254,  257,  262,  265,  268,  271,  276,  279,
      281,  284,  282,  289,  292,  302,  303,  762,  762,  250,
      229,  762,  762,  313,  762,  316,  337,  762,  248,  139,
      341,  323,  762,  762,  356,  305,  357,  359,  367,  368,
      370,  375,  376,  377,  382,  308,  384,  385,  387,  390,
      392,  398,  395,  404,  405,  417,  420,  422,  423,  431,
      428,  433,  434,  220,  213,  149,  436,  433,  762,  235,
      461,  762,  430,  444,  453,  460,  462,  477,  479,  485,
      487,  488,  493,  495,  496,  501,  502,  504,  507,  509,
      510,  512,  520,  517,  527,  518,  528,  530,  533,  536,

      539,  189,  175,  320,  542,  544,  559,  562,  569,  574,
      576,  577,  582,  583,  588,  589,  591,  596,  590,  597,
      598,  599,  604,  605,  612,  170,  158,  613,  615,  614,
      621,  622,  629,  637,  638,  640,  643,  646,  649,  651,
      652,  189,  137,  657,  662,  665,  667,  668,  670,    0,
      148,  673,  675,  676,  678,  146,  130,  438,  128,   73,
       85,  536,    0,   63,  557,    0,  762,  646,  762,  718,
      726,  732,  735,  736,  743,  747,  750,  753
    } ;

static yyconst flex_int16_t yy_def[279] =
    {   0,
      269,    1,  269,  269,  269,  269,  269,  270,  269,  269,
      269,  271,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  272,  269,
      269,  269,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  269,  269,  269,
      269,  269,  270,  269,  270,  269,  269,  269,  269,  269,
      269,  271,  271,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  273,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  270,  271,
      272,  269,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  273,  269,  269,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  269,  269,  269,  269,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  269,  269,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  269,  269,  272,  272,  272,  272,  272,  272,  274,
      269,  272,  272,  272,  272,  275,  276,  277,  275,  269,
      276,  269,  278,  269,  269,  278,  269,  269,    0,  269,
      269,  269,  269,  269,  269,  269,  269,  269
    } ;

static yyconst flex_uint16_t yy_nxt[828] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   29,   40,   29,   41,   29,   29,
       29,   29,   42,   43,   44,   45,   46,   47,   29,   29,
       29,   48,   49,   50,   51,   54,   56,   58,   59,   60,
       65,   57,   70,   67,   71,   71,   87,   88,   72,  122,
       66,   68,   69,   73,   61,  118,   54,  267,   75,   74,
       80,   80,   82,   54,   55,   75,   89,   76,   76,   77,

       90,  260,   78,   78,   63,   83,   77,   84,   85,   78,
       78,   79,   89,   77,   89,   55,   90,  264,   90,   78,
       77,   89,   55,  269,  119,   90,   78,   78,   89,   89,
       62,  258,   90,   90,   78,   89,   89,   79,   89,   90,
       90,   89,   90,   89,   89,   90,  260,   90,   90,  258,
       89,   89,   89,   95,   90,   90,   90,  131,  131,   89,
       96,   94,   93,   90,   98,  269,   97,  167,  167,  269,
      257,  103,  269,   99,  104,  106,  269,  100,  251,  101,
      109,  105,  107,  269,   71,   71,  108,  269,  102,  110,
      111,  117,  250,  124,  125,  115,  125,  114,  243,  112,

      126,  126,  113,   75,  116,   76,   76,  124,  125,  127,
      128,  242,  128,  125,   77,   78,   78,  129,  129,  136,
      130,  135,  130,  127,  128,  131,  131,  269,   77,  128,
      227,  269,   78,   75,  129,   80,   80,  269,  226,  269,
       78,  269,  129,  269,   77,  269,  269,   78,   78,  269,
      269,  269,  269,  171,  171,  269,  269,  269,   77,  269,
      203,  269,  269,  269,   78,  202,  269,  269,  165,  138,
      269,  269,   78,  269,  269,  137,  269,  269,  129,  129,
      269,  269,  140,  139,  269,  269,  269,  269,  269,  269,
      269,  269,  164,  269,  269,  129,  141,  269,  269,  142,

       63,  269,  143,  129,  145,  134,  144,  269,  269,  146,
      269,  269,  269,  269,  269,  133,  147,  269,  123,  150,
      149,  155,  148,  121,  153,  120,  166,  157,  166,  152,
      151,  167,  167,  269,  126,  126,  156,  159,  205,  205,
      158,  154,  175,  168,  169,  160,  169,  161,  163,  162,
      170,   92,  170,  173,  173,  171,  171,  168,  169,  131,
      131,  269,  269,  169,  269,  269,  269,   86,  269,  172,
      173,  172,  269,  269,   81,  269,  269,  269,  173,  269,
      269,  269,  269,  172,  269,  269,  269,  269,  172,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  176,  269,

      269,  269,   64,  269,  269,  180,  174,  269,  181,  269,
      269,  177,   63,  269,  269,   52,  182,  269,  184,  185,
      178,  179,  269,  269,  183,  269,  269,  269,  269,  269,
      187,  269,  269,  269,  186,  188,  269,  269,  269,  269,
      269,  269,  269,  269,  191,  192,  204,  189,  204,  269,
      190,  205,  205,  269,  167,  167,  262,  262,  269,  193,
      173,  173,  269,  196,  125,  269,  125,  269,  199,  269,
      200,  269,  194,  197,  195,  269,  198,  173,  125,  171,
      171,  201,  269,  125,  269,  173,  269,  269,  269,  128,
      269,  128,  269,  269,  269,  269,  269,  269,  269,  206,

      269,  269,  269,  128,  269,  269,  269,  269,  128,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  208,  269,  269,  269,  269,  269,
      269,  207,  269,  269,  210,  269,  269,  269,  269,  269,
      209,  269,  269,  269,  269,  269,  269,  211,  269,  269,
      212,  216,  265,  269,  262,  262,  219,  213,  221,  214,
      205,  205,  217,  215,  269,  218,  220,  269,  269,  269,
      169,  269,  169,  223,  269,  268,  268,  222,  269,  269,
      225,  269,  269,  269,  169,  269,  269,  269,  269,  169,
      224,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  228,  269,  269,  269,  230,  229,  269,  269,  269,
      269,  269,  269,  269,  269,  231,  269,  269,  269,  234,
      269,  269,  233,  235,  269,  236,  232,  269,  269,  239,
      269,  238,  269,  269,  237,  269,  269,  269,  269,  269,
      241,  269,  269,  240,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  246,  268,  268,  269,  269,  244,  245,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  247,  248,  269,  269,  269,  269,  269,  252,  249,

      269,  269,  269,  269,  269,  269,  269,  269,  254,  269,
      269,  255,  269,  269,  269,  269,  269,  253,   53,   53,
       53,   53,   53,   53,   53,   53,   62,   62,   62,  269,
       62,   62,   62,   62,   91,   91,  269,   91,   91,   91,
      132,  132,  256,  256,  259,  269,  269,  269,  259,  259,
      259,  261,  269,  261,  261,  263,  263,  263,  266,  266,
      266,    3,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

static yyconst flex_int16_t yy_chk[828] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,   10,   10,   11,
       16,    9,   19,   18,   19,   19,   27,   27,   20,   62,
       16,   18,   18,   20,   11,   49,   53,  264,   22,   20,
       22,   22,   25,   89,    8,   21,   29,   21,   21,   22,

       29,  261,   22,   22,   62,   25,   21,   25,   25,   21,
       21,   21,   33,   22,   34,   53,   33,  260,   34,   22,
       21,   35,   89,   63,   49,   35,   21,   22,   36,   38,
       63,  259,   36,   38,   21,   37,   39,   21,   40,   37,
       39,   41,   40,   44,   42,   41,  257,   44,   42,  256,
       43,   45,   47,   35,   43,   45,   47,  130,  130,   46,
       35,   34,   33,   46,   36,   91,   35,  166,  166,   91,
      251,   38,   93,   36,   38,   40,   93,   37,  243,   37,
       42,   39,   40,   94,   71,   71,   41,   94,   37,   43,
       43,   47,  242,   71,   71,   45,   71,   44,  227,   43,

       75,   75,   43,   76,   46,   76,   76,   71,   71,   75,
       75,  226,   75,   71,   76,   78,   78,   76,   76,   94,
       77,   93,   77,   75,   75,   77,   77,   95,   76,   75,
      203,   95,   78,   80,   76,   80,   80,   96,  202,   97,
       78,   96,   76,   97,   80,   98,   99,   80,   80,   98,
       99,  100,  101,  170,  170,  100,  101,  102,   80,  103,
      165,  102,  104,  103,   80,  164,  104,  105,  121,   96,
      106,  105,   80,  107,  106,   95,  108,  107,  129,  129,
      108,  109,   98,   97,  110,  109,  111,  113,  110,  112,
      111,  113,  120,  112,  114,  129,   99,  115,  114,  100,

       90,  115,  101,  129,  103,   88,  102,  116,  117,  104,
      136,  116,  117,  146,  136,   84,  105,  146,   70,  109,
      108,  112,  107,   57,  111,   56,  124,  113,  124,  110,
      109,  124,  124,   55,  126,  126,  112,  115,  204,  204,
      114,  111,  136,  126,  126,  115,  126,  116,  117,  116,
      127,   32,  127,  132,  132,  127,  127,  126,  126,  131,
      131,  135,  137,  126,  138,  135,  137,   26,  138,  131,
      132,  131,  139,  140,   23,  141,  139,  140,  132,  141,
      142,  143,  144,  131,  142,  143,  144,  145,  131,  147,
      148,  145,  149,  147,  148,  150,  149,  151,  137,  150,

      153,  151,   15,  152,  153,  140,  135,  152,  141,  154,
      155,  138,   12,  154,  155,    7,  142,    3,  144,  145,
      139,  139,  156,    0,  143,  157,  156,  158,  159,  157,
      149,  158,  159,  161,  147,  150,  160,  161,  162,  163,
      160,    0,  162,  163,  153,  154,  168,  151,  168,  174,
      152,  168,  168,  174,  167,  167,  258,  258,  175,  155,
      173,  173,  175,  158,  167,  176,  167,  177,  161,  176,
      162,  177,  156,  159,  157,    0,  160,  173,  167,  171,
      171,  163,  178,  167,  179,  173,  178,    0,  179,  171,
      180,  171,  181,  182,  180,    0,  181,  182,  183,  175,

      184,  185,  183,  171,  184,  185,  186,  187,  171,  188,
      186,  187,  189,  188,  190,  191,  189,  192,  190,  191,
        0,  192,  194,  196,  179,  193,  194,  196,    0,  193,
        0,  178,  195,  197,  181,  198,  195,  197,  199,  198,
      180,  200,  199,    0,  201,  200,    0,  184,  201,  206,
      185,  191,  262,  206,  262,  262,  194,  188,  196,  189,
      205,  205,  192,  190,  207,  193,  195,  208,  207,    0,
      205,  208,  205,  198,  209,  265,  265,  197,  209,  210,
      201,  211,  212,  210,  205,  211,  212,  213,  214,  205,
      200,  213,  214,  215,  216,  219,  217,  215,  216,  219,

      217,  218,  220,  221,  222,  218,  220,  221,  222,  223,
      224,  208,    0,  223,  224,  210,  209,  225,  228,  230,
      229,  225,  228,  230,  229,  211,  231,  232,    0,  216,
      231,  232,  214,  217,  233,  218,  213,    0,  233,  221,
        0,  220,  234,  235,  219,  236,  234,  235,  237,  236,
      224,  238,  237,  223,  239,  238,  240,  241,  239,    0,
      240,  241,  244,  232,  268,  268,  244,  245,  228,  229,
      246,  245,  247,  248,  246,  249,  247,  248,  252,  249,
      253,  254,  252,  255,  253,  254,    0,  255,    0,    0,
        0,  239,  240,    0,    0,    0,    0,    0,  244,  241,

        0,    0,    0,    0,    0,    0,    0,    0,  248,    0,
        0,  249,    0,    0,    0,    0,    0,  246,  270,  270,
      270,  270,  270,  270,  270,  270,  271,  271,  271,    0,
      271,  271,  271,  271,  272,  272,    0,  272,  272,  272,
      273,  273,  274,  274,  275,    0,    0,    0,  275,  275,
      275,  276,    0,  276,  276,  277,  277,  277,  278,  278,
      278,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.l"
#line 11 "parser.l"
int yylineno;
#include <stdio.h> 
#line 740 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 15 "parser.l"

#line 960 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 270 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 762 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "parser.l"
{ yylineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "parser.l"
{ multicomment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "parser.l"
{ singlecomment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "parser.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "parser.l"
{ return DEF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "parser.l"
{ return DEF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "parser.l"
{ return DEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 28 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "parser.l"
{  return CONSTANT; }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 32 "parser.l"
{  return STRING_LITERAL; } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "parser.l"
{  return SIZEOF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "parser.l"
{  return PTR_OP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "parser.l"
{  return INC_OP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "parser.l"
{  return DEC_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "parser.l"
{  return LEFT_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "parser.l"
{  return RIGHT_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "parser.l"
{  return LE_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "parser.l"
{  return GE_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "parser.l"
{  return EQ_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "parser.l"
{  return NE_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "parser.l"
{  return AND_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "parser.l"
{  return OR_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "parser.l"
{  return MUL_ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "parser.l"
{  return DIV_ASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "parser.l"
{  return MOD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "parser.l"
{  return ADD_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "parser.l"
{  return SUB_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "parser.l"
{  return LEFT_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "parser.l"
{  return RIGHT_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "parser.l"
{  return AND_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "parser.l"
{  return XOR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "parser.l"
{  return OR_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "parser.l"
{  return TYPEDEF; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "parser.l"
{  return EXTERN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "parser.l"
{  return STATIC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "parser.l"
{  return AUTO; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "parser.l"
{  return REGISTER; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "parser.l"
{  return CHAR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "parser.l"
{  return SHORT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "parser.l"
{  return INT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "parser.l"
{  return LONG; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "parser.l"
{  return SIGNED; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "parser.l"
{  return UNSIGNED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "parser.l"
{  return FLOAT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "parser.l"
{  return DOUBLE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "parser.l"
{  return CONST; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "parser.l"
{  return VOLATILE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "parser.l"
{  return VOID; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "parser.l"
{  return STRUCT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "parser.l"
{  return UNION; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "parser.l"
{  return ENUM; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "parser.l"
{  return ELLIPSIS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "parser.l"
{  return CASE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "parser.l"
{  return DEFAULT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "parser.l"
{  return IF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "parser.l"
{  return ELSE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "parser.l"
{  return SWITCH; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "parser.l"
{  return WHILE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "parser.l"
{  return DO; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "parser.l"
{  return FOR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "parser.l"
{  return GOTO; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "parser.l"
{  return CONTINUE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "parser.l"
{  return BREAK; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "parser.l"
{  return RETURN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "parser.l"
{  return(';'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "parser.l"
{  return('{'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "parser.l"
{  return('}'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "parser.l"
{  return(','); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "parser.l"
{  return(':'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "parser.l"
{  return('='); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "parser.l"
{  return('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "parser.l"
{  return(')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "parser.l"
{  return('['); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "parser.l"
{  return(']'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "parser.l"
{  return('.'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "parser.l"
{  return('&'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "parser.l"
{  return('!'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "parser.l"
{  return('~'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "parser.l"
{  return('-'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "parser.l"
{  return('+'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "parser.l"
{  return('*'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "parser.l"
{  return('/'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "parser.l"
{  return('%'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "parser.l"
{  return('<'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "parser.l"
{  return('>'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "parser.l"
{  return('^'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "parser.l"
{  return('|'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "parser.l"
{  return('?'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "parser.l"
{  return IDENTIFIER; }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 112 "parser.l"
{  }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "parser.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "parser.l"
ECHO;
	YY_BREAK
#line 1516 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 270 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 269);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 114 "parser.l"


yywrap()
{
	return(1);
}
multicomment()
{
	char c, c1;
	while ((c = input()) != '*' && c != 0);
	c1=input();
	if(c=='*' && c1=='/')
	{
		c=0;
	}
	if (c != 0)
		putchar(c1);
}
singlecomment()
{
	char c;
	while(c=input()!='\n');
	if(c=='\n')
		c=0;
	if(c!=0)
		putchar(c);
}

